### ISSUE TITLE
使用golang读取windows注册表

### ISSUE THREAD

**Issue by Wusuluren** [wuranxu/goBoss#1]
使用golang.org/x/sys/windows/registry库可以读取注册表，不需要getWinReg.exe了。代码如下：
```golang
func getWinChromeVer() string {
	key, err := registry.OpenKey(registry.CURRENT_USER, config.ChromeReg, registry.ALL_ACCESS)
	if err != nil {
		log.Fatal("获取Windows Chrome版本失败!请检查Chrome是否安装 Error: ", err)
	}
	defer key.Close()
	s, _, _ := key.GetStringValue("version")
	return strings.Split(s, ".")[0]
}
```

**Comment by wuranxu** [comment]
感谢提醒 因为在mac os下go build无法通过, golang.org/x/sys/windows/registry库内容全部被注释掉(因为macos下没有注册表的概念), 所以为了同时支持mac和windows, 故将获取注册表的代码单独打包成exe供windows用户使用了。暂时没有找到其他可行的办法···如有提供，十分感谢。

下图是driver目录下的获取注册表代码的截图。

![image.png](https://upload-images.jianshu.io/upload_images/6053915-444ef389f577e62a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by Wusuluren** [comment]
是我太粗心了，没看到这个文件，不过也知道了原来mac系统里golang会屏蔽库的这部分代码。下面这个是直接调用windows命令来获取注册表的，可以了解一下，不过读的是HKEY_CURRENT_USER，这个不确定是否一定能正确获取chrome版本，读取HKEY_USERS的话ssid比较麻烦，可以参考[这里](https://stackoverflow.com/questions/2919286/getting-the-username-from-the-hkey-users-values)：
```golang
func getWinChromeVer() string {
	cmd := exec.Command("reg", "query", `HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon`, "/v", "version")
	cmdOutput := &bytes.Buffer{}
	cmd.Stdout = cmdOutput
	err := cmd.Run()
	if err != nil {
		log.Fatal("获取Windows Chrome版本失败!请检查Chrome是否安装 Error: ", err)
	}
	ver := string(cmdOutput.Bytes())
	verList := strings.Split(ver, " ")
	ver = verList[len(verList)-1]
	 //fmt.Println(ver)
	verList = strings.Split(ver, ".")
	ver = verList[0]
	//fmt.Println(verList[0])
	return ver
}
```

**Comment by wuranxu** [comment]
十分感谢···有windows命令能获取的话，就不需要exe文件了。有空会修改，多谢~~
